site_name: My Docs
site_url: https://zahirabbask.github.io/
theme:
  name: mkdocs
  nav_style: dark
nav:
    - Home: index.md
    - Article: article.md
    - 'Subject1':
    - 'dir/file1.md'
    - 'dir/file2.md'
    - 'Subject2':
    - 'NestedSubject2_1':
      - 'dir/file1.md'
      - 'dir/file2.md'
    - 'NestedSubject2_2':
      - 'dir/file.md'
      - 'dir/file2.md'
      - 'dir/file3.md'
      - 'dir/file4.md'
